spring.application.name=animaxx

spring.datasource.url=jdbc:mysql://localhost:3306/animaxx
spring.datasource.username=root
spring.datasource.password=Krishna30@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080